apiVersion: v1
kind: Secret
metadata:
  name: platform-runtime-secrets
  namespace: apps
type: Opaque
stringData:
  auth-connection-string: "Host=<rds-endpoint>;Database=platform;Username=platform_admin;Password=<password>"
  auth-jwt-secret: "<replace-with-32-byte-secret>"
  auth-bootstrap-admin-email: "admin@logistics.local"
  auth-bootstrap-admin-password: "<replace-me>"
  shipment-connection-string: "Host=<rds-endpoint>;Database=platform;Username=platform_admin;Password=<password>"
  tracking-connection-string: "Host=<rds-endpoint>;Database=platform;Username=platform_admin;Password=<password>"
  platform-trusted-proxy-secret: "<replace-with-32-byte-secret>"
  platform-internal-service-secret: "<replace-with-32-byte-secret>"
