{{- $root := . -}}
{{- range $serviceKey, $service := .Values.services }}
{{- if and $service.enabled $service.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $service.serviceAccount.name }}
  namespace: {{ $root.Values.namespace.name }}
  labels:
{{ include "platform-services.labels" (dict "root" $root "service" $service) | indent 4 }}
  annotations:
{{- if gt (len $service.serviceAccount.annotations) 0 }}
{{ toYaml $service.serviceAccount.annotations | indent 4 }}
{{- else }}
    {}
{{- end }}
{{- end }}
{{- end }}
